export const LOCATIONS = [
  {
    id: "launch_site",
    name: "Ракетная шахта",
    type: "clan",
    x: 72,
    y: 18,
    icon: "Rocket",
    color: "text-red-400",
    dot: "bg-red-500",
    loot: ["Военные ящики", "Элитные ящики", "Научный ящик"],
    desc: "Крупная военная локация. Много лута, часто посещается.",
    danger: 5,
  },
  {
    id: "excavator",
    name: "Гигантский экскаватор",
    type: "clan",
    x: 58,
    y: 30,
    icon: "Cog",
    color: "text-yellow-400",
    dot: "bg-yellow-500",
    loot: ["Дизельное топливо", "Серный металл", "Компоненты"],
    desc: "Пассивная добыча ресурсов. Нужна защита от рейдов.",
    danger: 5,
  },
  {
    id: "military_tunnels",
    name: "Военные тоннели",
    type: "clan",
    x: 40,
    y: 22,
    icon: "Shield",
    color: "text-red-500",
    dot: "bg-red-600",
    loot: ["Военные ящики", "Оружие", "Бронежилеты"],
    desc: "Сложные тоннели с учёными. Элитный лут.",
    danger: 5,
  },
  {
    id: "airfield",
    name: "Аэродром",
    type: "squad",
    x: 25,
    y: 35,
    icon: "Plane",
    color: "text-blue-400",
    dot: "bg-blue-500",
    loot: ["Военные ящики", "Оружие", "Топливо"],
    desc: "Большая открытая локация. Хороший лут, много PvP.",
    danger: 4,
  },
  {
    id: "dome",
    name: "Купол (Сфера)",
    type: "squad",
    x: 65,
    y: 55,
    icon: "Globe",
    color: "text-purple-400",
    dot: "bg-purple-500",
    loot: ["Военные ящики", "Синие карты", "Оружие"],
    desc: "Опасная сфера с хорошим лутом. Требует паркура.",
    danger: 4,
  },
  {
    id: "water_treatment",
    name: "Очистные сооружения",
    type: "squad",
    x: 48,
    y: 68,
    icon: "Droplets",
    color: "text-cyan-400",
    dot: "bg-cyan-500",
    loot: ["Синие карты", "Военный лут", "Компоненты"],
    desc: "Большая открытая локация с синими картами доступа.",
    danger: 4,
  },
  {
    id: "gas_station",
    name: "Заправка",
    type: "duo",
    x: 30,
    y: 60,
    icon: "Fuel",
    color: "text-green-400",
    dot: "bg-green-500",
    loot: ["Зелёные ящики", "Баррели", "Компоненты"],
    desc: "Небольшая безопасная локация для старта. Хороша для дуо.",
    danger: 2,
  },
  {
    id: "supermarket",
    name: "Супермаркет",
    type: "duo",
    x: 55,
    y: 78,
    icon: "ShoppingCart",
    color: "text-green-300",
    dot: "bg-green-400",
    loot: ["Зелёные ящики", "Еда", "Базовые ресурсы"],
    desc: "Популярное место для дуо. Быстрый лут на старте.",
    danger: 2,
  },
  {
    id: "warehouse",
    name: "Склад",
    type: "duo",
    x: 78,
    y: 48,
    icon: "Warehouse",
    color: "text-amber-400",
    dot: "bg-amber-500",
    loot: ["Синие ящики", "Промышленные компоненты", "Металл"],
    desc: "Средняя локация с хорошим промышленным лутом.",
    danger: 3,
  },
  {
    id: "outpost",
    name: "Аванпост",
    type: "solo",
    x: 20,
    y: 75,
    icon: "Home",
    color: "text-zinc-400",
    dot: "bg-zinc-500",
    loot: ["Безопасная зона", "Магазины", "Верстаки"],
    desc: "Нейтральная безопасная зона. Идеальна для соло-торговли.",
    danger: 0,
  },
  {
    id: "bandit_camp",
    name: "Лагерь бандитов",
    type: "solo",
    x: 82,
    y: 72,
    icon: "Skull",
    color: "text-zinc-400",
    dot: "bg-zinc-500",
    loot: ["Казино", "Магазины", "Лечение"],
    desc: "Нейтральная зона. Можно продать/купить ресурсы.",
    danger: 0,
  },
]

export const ANIMALS = [
  { id: "wolf", name: "Волки", icon: "🐺", color: "text-zinc-300", desc: "Агрессивны. Дают мясо и шкуру." },
  { id: "bear", name: "Медведи", icon: "🐻", color: "text-amber-700", desc: "Очень опасны. Много мяса и жира." },
  { id: "boar", name: "Кабаны", icon: "🐗", color: "text-amber-600", desc: "Умеренно опасны. Мясо и кости." },
  { id: "cloth", name: "Ткань (конопля)", icon: "🌿", color: "text-green-400", desc: "Растёт на полях. Нужна для одежды." },
  { id: "ore", name: "Руда", icon: "⛏️", color: "text-stone-400", desc: "Металлические и серные узлы руды." },
]

export const TEAM_TYPES = [
  {
    id: "solo",
    name: "Соло",
    icon: "User",
    color: "text-zinc-400",
    border: "border-zinc-600",
    bg: "bg-zinc-800/50",
    activeBg: "bg-zinc-700",
    desc: "Тихие места вдали от крупных локаций",
    locations: ["outpost", "bandit_camp"],
    tip: "Держись подальше от крупных точек. Ищи тихий лес или берег у края карты.",
  },
  {
    id: "duo",
    name: "Дуо",
    icon: "Users",
    color: "text-green-400",
    border: "border-green-700",
    bg: "bg-green-950/30",
    activeBg: "bg-green-900/50",
    desc: "Возле заправки, супермаркета, склада",
    locations: ["gas_station", "supermarket", "warehouse"],
    tip: "Селись у средних монументов. Быстрый лут и неплохая защита от набегов.",
  },
  {
    id: "squad",
    name: "Сквад",
    icon: "Users",
    color: "text-blue-400",
    border: "border-blue-700",
    bg: "bg-blue-950/30",
    activeBg: "bg-blue-900/50",
    desc: "Аэродром, купол, очистные сооружения",
    locations: ["airfield", "dome", "water_treatment"],
    tip: "Выбирай сильные монументы с военным лутом. Контролируй зону вместе.",
  },
  {
    id: "clan",
    name: "Клан",
    icon: "Crown",
    color: "text-orange-400",
    border: "border-orange-700",
    bg: "bg-orange-950/30",
    activeBg: "bg-orange-900/50",
    desc: "Космодром, экскаватор, военные тоннели",
    locations: ["launch_site", "excavator", "military_tunnels"],
    tip: "Занимай топовые монументы. Только клан способен удержать Ракетную шахту.",
  },
]

export const DANGER_LABELS = ["Мирно", "Спокойно", "Умеренно", "Опасно", "Очень опасно", "Экстремально"]
export const DANGER_COLORS = ["text-zinc-400", "text-green-400", "text-yellow-400", "text-orange-400", "text-red-400", "text-red-600"]
